### ISSUE TITLE
v1.1.1 doesn't have any TS types

### ISSUE THREAD

**Issue by adambiggs** [siberiacancode/lodash-omitdeep#2]
Getting `TS7016: Could not find a declaration file for module 'lodash-omitdeep'`

**Comment by debabin** [comment]
Yes it was bug of version 1.1.1, fixed in 1.2.0. Sorry for the inconvenience, please use 1.2.0 ✌️

**Comment by debabin** [comment]
Can i close issue ? @adambiggs
